server:
  port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
        username: kingeid
        password: 123456

#自定义配置
resources:
    midpHost: 1.1.1.1

#jwt配置
jwt:
    EXPIRATIONTIME: 1000
    SECRET: OHAHAHAHA
