server:
  port: 9000

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
        username: kingeid
        password: 123456
        
#自定义配置
resources:
    logdir: logs/
    midpHost: 1.1.1.1